>P1;SH2B
structureX:SH2B:1: : 108  : :  : : -1.00 :-1.00
NNLETYEWYNKSISRDKAEKLLLDTGKEGAFMVRDSR-TPGTYTVSVFTKAIISENPCIK
HYHIKETNDSPKRYYVAEKYVFDSIPLLIQYHQYNGGGLVTRLRYPVCG*
>P1;SH2BM
structureX:SH2BM:1: : 108  : :  : : -1.00 :-1.00
NNLETYEWYNKSISRDKAEKLRLDTGKEGAFMVRDSR-TPGTYTVSVFTKAIISENPCIK
HYHIKETNDSPKRYYVAEKYVFDSIPLLIQYHQYNGGGLVTRLRYPVCG*
