>P1;target
structureX:target:1: : 439  : :  : : -1.00 :-1.00
-----------------MFRKSVRPLVGAAL-----------------------------
------------------------------------------------------VMAAAV
AAGPTPASAAESEFYVNPDMASAQWVR-DNPQDSRADVIANRVADVPQGTWFTSYNPNEV
QGQVDALVGSAESAGKTP----IMVVYNIPNRDCSNHSGGGA----P-DHSSYRDWVDQV
AAGLNGRP---ATIVVEPDVLSLMDSCMDQ----SQQNHVMDSIAYAGKTLMAGSSQARV
YFDAGHSGWHS-PGEI-------ASRLNGADIANSAHGIATNTSNYNWT-----------
---DDEVSYTRQIIDATGHSGLRA--VVDTSRNGNGPQ----GSEWCDPEGRAIGTESTT
NTGSSHVDAFLWVKLPGEADGCAAGA----------------------------------
-----GEFVPQLAYDMAVAADPEPDPEPSPDPEPTPDPEPTPEPGEGCEAAYSVANEWSD
GFQAEVTVTAGADLDGWEVAIDFPDGQGIEQAWNAEVSGSGGAYTASDVSHNGSLSAGES
TGFGFTGTHSGANGEPELTCSAA*
>P1;2bodX
structureX:2bodX:1: : 279  : :  : : -1.00 :-1.00
DSPFYVNPNMSSAEWVRNNPNDPRTPVIRDR-----------------------------
------------------------------------------------------------
------------------------------------------IASVPQGTWFAHHNPGQI
TGQVDAL-MSAAQAAG---KIPILVVYNAPGRDCGAPSH-----------SAYRSWIDEF
AAGLKNRPA---YIIVEPDLISLMS-----SCMQHVQQEVLETMAYAGKALKAGSSQARI
YFDAGHSAWHS-PAQM-------ASWLQQADISNSAHGIATNTSNYR-W-----------
--TADEVAYAKAVLSAIGNPSLRA--VIDTSRNGNGPA----GNEWCDPSGRAIGTPSTT
NTGDPMIDAFLWIKLPGEADGCI-------------------------------------
-----AGAGQFVPQAAYEMAIAA-------------------------------------
------------------------------------------------------------
-----------------------*
