>P1;target
structureX:target:1: : 381  : :  : : -1.00 :-1.00
MASSTQ------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------GQVITCKAAVAWEANKPMTIEDVQVAPPQAGEVRVKILFT
ALCHTDHYTWSGKDPEGLFPCILGHEAAGIVESVGEGVTEVQPGDHVIPCYQAECRECKF
CKSGKTNLCGKVRAATGVGVMMNDRKSRFSINGKPIYHFMGTSTFSQYTVVHDVSVAKIN
PQAPLDKVCLLGCGVSTGLGAVWNTAKVEAGSIVAIFGLGTVGLAVAEGAKSAGASRIIG
IDIDSKKFDVAKNFGVTEFVNPKDHDKPIQQVIVDLTDGGVDYSFECIGNVSVMRSALEC
CHKGWGTSVIVGVAASGQEISTRPFQLVTGRVWKGTAFGGFKSRSQVPWLVEKYLNKEIK
VDEYVTHSMNLTDINKAFDLLHEGGCLRCVL--ATDK*
>P1;1mc5A
structureX:1mc5A:1: : 373  : :  : : -1.00 :-1.00
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------ANEVIKCKAAVAWEAGKPLSIEEIEVAPPKAHEVRIKIIAT
AVCHTDAYTLSGADPEGCFPVILGHEGAGIVESVGEGVTKLKAGDTVIPLYIPQCGECKF
CLNPKTNLCQKIRVTQGKGL-MPDGTSRFTCKGKTILHYMGTSTFSEYTVVADISVAKID
PLAPLDKVCLLGCGISTGYGAAVNTAKLEPGSVCAVFGLGGVGLAVIMGCKVAGASRIIG
VDINKDKFARAKEFGATECINPQDFSKPIQEVLIEMTDGGVDYSFECIGNVKVMRAALEA
CHKGWGVSVVVGVAASGEEIATRPFQLVTGRTWKGTAFGGWKSVESVPKLVSEYMSKKIK
VDEFVTHNLSFDEINKAFELMHSGKSIRTVVKI----*
