>P1;1mc5_A
structureX:1mc5_A:1: : 373  : :  : : -1.00 :-1.00
------A-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------NEVIKCKAAVAWEAGKPLSIEEIEVAPPKA
HEVRIKIIATAVCHTDAYTLSGADPEGCFPVILGHEGAGIVESVGEGVTKLKAGDTVIPL
YIPQCGECKFCLNPKTNLCQKIRVTQGKGL-MPDGTSRFTCKGKTILHYMGTSTFSEYTV
VADISVAKIDPLAPLDKVCLLGCGISTGYGAAVNTAKLEPGSVCAVFGLGGVGLAVIMGC
KVAGASRIIGVDINKDKFARAKEFGATECINPQDFSKPIQEVLIEMTDGGVDYSFECIGN
VKVMRAALEACHKGWGVSVVVGVAASGEEIATRPFQLVTGRTWKGTAFGGWKSVESVPKL
VSEYMSKKIKVDEFVTHNLSFDEINKAFELMHSGKSIRTVVKI----*
>P1;target
structureX:target:1: : 381  : :  : : -1.00 :-1.00
MASSTQG-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------QVITCKAAVAWEANKPMTIEDVQVAPPQA
GEVRVKILFTALCHTDHYTWSGKDPEGLFPCILGHEAAGIVESVGEGVTEVQPGDHVIPC
YQAECRECKFCKSGKTNLCGKVRAATGVGVMMNDRKSRFSINGKPIYHFMGTSTFSQYTV
VHDVSVAKINPQAPLDKVCLLGCGVSTGLGAVWNTAKVEAGSIVAIFGLGTVGLAVAEGA
KSAGASRIIGIDIDSKKFDVAKNFGVTEFVNPKDHDKPIQQVIVDLTDGGVDYSFECIGN
VSVMRSALECCHKGWGTSVIVGVAASGQEISTRPFQLVTGRVWKGTAFGGFKSRSQVPWL
VEKYLNKEIKVDEYVTHSMNLTDINKAFDLLHEGGCLRCVL--ATDK*
