>P1;target
structureX:target:1: : 423  : :  : : -1.00 :-1.00
---------------------------------MSSQVVGIEPLYIKAEPASPDSPKGSS
ETETEPPVALAPGPAPTRCLPGHKEEEDGEGAGPGEQGGGKLVLSSLPKR-LCLVCGDVA
SGYHYGVASCEACKAFFKRTIQGSIEYSCPASNECEITKRRRKACQACRFTKCLRVGML-
KEGVRLDRVRGGRQKYKRRPEVDPLPFPGPFPAGPLAVAGGPRKTAAPVNALVSHLLVVE
PEKLYAMPDPAGPDGHLPAVATLCDLFDREIVVTISWAKSIPGFSSLSLSDQMSVLQSVW
MEVLVLGVAQRSLPLQDELAFAEDLVLDEEGARAAGLGELGAALLQLVRRLQALRLEREE
YVLLKALALANSDSVHIEDAEAVEQLREALHEALLEYEAGRAGPGGGAERRRAGRLLLTL
PLLRQTAGKVLAHFYGVKLEGKVPMHKLFLEMLEAMMD*
>P1;3d24A
structureX:3d24A:1: : 209  : :  : : -1.00 :-1.00
VNALVSHLLVVEPEKLYAMPAVATLCDLFDREIVVTISWAKSIPGFSSLSLSDQMSVLQS
VWMEVLVLGVAQRSLPLQDELAFAEDLVLDEEGARAAGLGELGAALLQLV----------
------------------------------------------R-----------------
RLQALRLEREEYVLLKALALANSDSVHIEDAEAVEQLREALHEALLEYEAGERRRAGRLL
LTLPLLRQTAGKVLAHFYGVKLEGKVPMHKLFLEMLEA----------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------*
