>P1;target.dsspSeq
target.dsspSeq 
VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNAL
SALSDDEAHKERDDPVNDKLLSHCLLVTLAAHAPALAHLPAEFTPAVHASLDKFLASVSTVDTSKYR*
>P1;target.dsspSS
target.dsspSS 
---SSHHHHHHHHHHHS-TTTTHHHHHHHHHHHHH--GGGGG-SSS--SSS-TTHHHHHHHHHHHHEETEESTTT-SSST
HHHHHHHTTTS---THHHHTTHHHHS--TTTT-TTTTT-TTT--SSTTTTHHHHHHHHHHTTSSS--*
