>P1;target
structureX:target:1: : 147  : :  : : -1.00 :-1.00
VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS----HGSAQV
KGHGKKVADALTNAVAHV--D-DMPNALSALSDDEAHKERD-DPVNDKLLSHCL-LVTLA
AHAPALAHLPAEFTPAVHASLDKFLASVSTVDTSKYR*
>P1;template
structureX:template:1: : 147  : :  : : -1.00 :-1.00
VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS----HGSAQV
KGHGKKVADALTNAVAHV--D-DMPNALSALSDDEAHKERD-DPVNDKLLSHCL-LVTLA
AHAPALAHLPAEFTPAVHASLDKFLASVSTVDTSKYR*
