>P1;tout
structureX:tout:1: : 147  : :  : : -1.00 :-1.00
VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGK
KVADALTNAVAHVDDMPNALSALSDDEAHKERDDPVNDKLLSHCLLVTLAAHAPALAHLP
AEFTPAVHASLDKFLASVSTVDTSKYR*
>P1;target
structureX:target:1: : 147  : :  : : -1.00 :-1.00
VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGK
KVADALTNAVAHVDDMPNALSALSDDEAHKERDDPVNDKLLSHCLLVTLAAHAPALAHLP
AEFTPAVHASLDKFLASVSTVDTSKYR*
