>P1;target
structureX:target:1: : 401  : :  : : -1.00 :-1.00
MKLFTSTLTAKKSSTHKPLISLALSVLISTLLISE-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------TAQAADANDRLEQEVDKQAKQLMAQYQIPGMAFGIIVDGKSHFYNYGL
ADKQRNQPVSEDTIFELGSVSKTFAATLASYSELNGTLSLDDTADKYIPYLKNSAIGNTK
LISLVTYSAGGYHYRCLKTLENNKELLQYYKSWHPDFPVNSKRLYSNASIGLFGYISALS
MHSDYTKLIENTVLPSLKMTNTFVDVPANKMEDYAFGYNAAGEPIRVNPGMLDAEAYGIK
STSADMTRFMAANMGLVTVDS-QMQQALDNNRKGYYRTKSFTQGLAWEMYPLPTTLQQLV
EGNSTETILQPQPIQLNEPPTPVLNDVWVNKTGATNGFGAYIAYMPAKKTGMFILANKNY
PNTERVKAAYTILDS--VMNN-----------*
>P1;1fr6B
structureX:1fr6B:1: : 361  : :  : : -1.00 :-1.00
-------------------------------AAKT-EQQIADIVNRTITPLMQEQAIPGM
AVAIIYQGKPYYFTWGKADIANNRPVTQQTLFELGSVSKTFNGVLGGDAIARGEIKLSDP
VTQYWPELTGKQWQGISLLHLATYTAGGLPLQVPDDVTDKAALLRFYQNWQPQWAPGAKR
LYANSSIGLFGALAVKPSGMSYEEAMSKRVLHPLKLAHTWITVPQSEQKDYAWGYREGKP
VHVSPGQLDAEAYGVKSSVIDMTRWVQANMDASQVQEKTLQQGIELAQSRYWRIGDMYQG
LGWEMLNWPVKADSIISGSDSKVALAALPAVEVNPPAPAVKASWVHKTGSTGGFGSYVAF
VPEKNLGIVMLANKSYP-N-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------PVRVEAAWRILEKLQ*
