-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-23 17:48:01 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE entity_3 
    
    -- No Columns 
;

CREATE TABLE product (
    product_id NUMBER NOT NULL,
    barcode    CHAR(6 CHAR) NOT NULL,
    units      INTEGER,
    price      NUMBER(4, 2),
    brand      CHAR(20 CHAR),
    name       CHAR(20 CHAR)
);

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );

ALTER TABLE product ADD CONSTRAINT product_barcode_un UNIQUE ( barcode );

CREATE TABLE relation_1 (
    product_product_id NUMBER NOT NULL,
    ticket_ticket_id   NUMBER NOT NULL
);

ALTER TABLE relation_1 ADD CONSTRAINT relation_1_pk PRIMARY KEY ( product_product_id,
                                                                  ticket_ticket_id );

CREATE TABLE ticket (
    ticket_id    NUMBER NOT NULL,
    total_amount NUMBER,
    date_ck      DATE NOT NULL,
    form_payment unknown 
--  ERROR: Datatype UNKNOWN is not allowed 

);

ALTER TABLE ticket ADD CONSTRAINT ticket_pk PRIMARY KEY ( ticket_id );

ALTER TABLE ticket ADD CONSTRAINT ticket_date_ck_un UNIQUE ( date_ck );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_product_fk FOREIGN KEY ( product_product_id )
        REFERENCES product ( product_id );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_ticket_fk FOREIGN KEY ( ticket_ticket_id )
        REFERENCES ticket ( ticket_id );

CREATE SEQUENCE product_product_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER product_product_id_trg BEFORE
    INSERT ON product
    FOR EACH ROW
    WHEN ( new.product_id IS NULL )
BEGIN
    :new.product_id := product_product_id_seq.nextval;
END;
/

CREATE SEQUENCE ticket_ticket_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER ticket_ticket_id_trg BEFORE
    INSERT ON ticket
    FOR EACH ROW
    WHEN ( new.ticket_id IS NULL )
BEGIN
    :new.ticket_id := ticket_ticket_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
